[package]
name = "invader-macro"
version = "0.1.0"
authors = ["TechnoElf <jhjavadev@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
proc-macro2 = "1.0.10"
syn = { version = "1.0.17", features = ["extra-traits"] }
